use std::io::Write;

use mlx_rs::error::Exception;
use serde_json::json;
use tempfile::NamedTempFile;

use super::*;
use crate::modernbert::config::tests::test_config;

fn tiny_config() -> Config {
    Config {
        vocab_size: 8,
        hidden_size: 4,
        intermediate_size: 6,
        num_attention_heads: 2,
        ..test_config()
    }
}

// Independent two-layer fixture, not generated by expected_shapes. In
// particular layer zero has no attn_norm and only the classifier has bias.
fn tiny_header(kind: WeightKind) -> Value {
    let prefix = if matches!(kind, WeightKind::Reranker) {
        "model."
    } else {
        ""
    };
    let mut tensors = vec![
        ("embeddings.tok_embeddings.weight", vec![8, 4]),
        ("embeddings.norm.weight", vec![4]),
        ("final_norm.weight", vec![4]),
        ("layers.0.attn.Wqkv.weight", vec![12, 4]),
        ("layers.0.attn.Wo.weight", vec![4, 4]),
        ("layers.0.mlp.Wi.weight", vec![12, 4]),
        ("layers.0.mlp.Wo.weight", vec![4, 6]),
        ("layers.0.mlp_norm.weight", vec![4]),
        ("layers.1.attn_norm.weight", vec![4]),
        ("layers.1.attn.Wqkv.weight", vec![12, 4]),
        ("layers.1.attn.Wo.weight", vec![4, 4]),
        ("layers.1.mlp.Wi.weight", vec![12, 4]),
        ("layers.1.mlp.Wo.weight", vec![4, 6]),
        ("layers.1.mlp_norm.weight", vec![4]),
    ]
    .into_iter()
    .map(|(key, shape)| (format!("{prefix}{key}"), shape))
    .collect::<Vec<_>>();
    if matches!(kind, WeightKind::Reranker) {
        tensors.extend([
            ("head.dense.weight".into(), vec![4, 4]),
            ("head.norm.weight".into(), vec![4]),
            ("classifier.weight".into(), vec![1, 4]),
            ("classifier.bias".into(), vec![1]),
        ]);
    }
    let mut header = json!({"__metadata__": {"format": "pt"}});
    let mut offset = 0;
    for (key, shape) in tensors {
        let end = offset + shape.iter().product::<usize>() * 4;
        header[key] = json!({"dtype":"F32", "shape":shape, "data_offsets":[offset,end]});
        offset = end;
    }
    header
}

fn payload_len(header: &Value) -> u64 {
    header
        .as_object()
        .unwrap()
        .values()
        .filter_map(|tensor| tensor["data_offsets"][1].as_u64())
        .max()
        .unwrap()
}

fn write_file(bytes: &[u8], payload_len: u64) -> NamedTempFile {
    let mut file = NamedTempFile::new().unwrap();
    file.write_all(&(bytes.len() as u64).to_le_bytes()).unwrap();
    file.write_all(bytes).unwrap();
    // Sparse zero-filled payload, including for the large official headers.
    file.as_file()
        .set_len(8 + bytes.len() as u64 + payload_len)
        .unwrap();
    file
}

fn fixture(header: &Value) -> NamedTempFile {
    write_file(&serde_json::to_vec(header).unwrap(), payload_len(header))
}

#[test]
fn accepts_complete_synthetic_and_fixed_official_headers() {
    for kind in [WeightKind::Embed, WeightKind::Reranker] {
        let file = fixture(&tiny_header(kind));
        validate(file.path(), &tiny_config(), kind).unwrap();
    }
    for (kind, config, header) in [
        (
            WeightKind::Embed,
            include_str!("../../../tests/fixtures/modernbert_configs/ruri-v3-310m.json"),
            include_bytes!("../../../tests/fixtures/modernbert_weights/ruri-v3-310m.header.json")
                .as_slice(),
        ),
        (
            WeightKind::Reranker,
            include_str!("../../../tests/fixtures/modernbert_configs/ruri-v3-reranker-310m.json"),
            include_bytes!(
                "../../../tests/fixtures/modernbert_weights/ruri-v3-reranker-310m.header.json"
            )
            .as_slice(),
        ),
    ] {
        let config: Config = serde_json::from_str(config).unwrap();
        let value: Value = serde_json::from_slice(header).unwrap();
        let file = write_file(header, payload_len(&value));
        validate(file.path(), &config, kind).unwrap();
    }
}

/// Called through each production loader, without MLX allocation. Each case
/// changes one condition of a complete file, so another failure cannot mask it.
pub(crate) fn assert_loader_rejects(
    kind: WeightKind,
    load: impl Fn(&Path, &Config) -> Result<(), Exception>,
) {
    let config = tiny_config();
    let valid = tiny_header(kind);
    let check = |header: &Value, reason: &str| {
        let file = fixture(header);
        let err = load(file.path(), &config).expect_err(reason);
        assert!(
            err.what().contains(reason),
            "expected {reason}, got {}",
            err.what()
        );
    };
    for key in valid
        .as_object()
        .unwrap()
        .keys()
        .filter(|k| *k != "__metadata__")
    {
        let mut header = valid.clone();
        header.as_object_mut().unwrap().remove(key);
        check(&header, &format!("weights: missing key: {key}"));
    }
    let key = if matches!(kind, WeightKind::Embed) {
        "final_norm.weight"
    } else {
        "classifier.bias"
    };
    let mut header = valid.clone();
    header[key]["shape"] = json!([2, 2]);
    check(&header, &format!("weights: shape: {key}"));
    for dtype in ["F16", "BF16", "I32", "F64"] {
        let mut header = valid.clone();
        header[key]["dtype"] = json!(dtype);
        check(&header, &format!("weights: dtype: {key}"));
    }
    for unknown in [
        "head.dense.bias",
        "head.norm.bias",
        "decoder.weight",
        "layers.0.attn_norm.weight",
        "rotary_emb.inv_freq",
    ] {
        let mut header = valid.clone();
        header[unknown] = valid[key].clone();
        check(&header, &format!("weights: unknown key: {unknown}"));
    }
}

#[test]
fn malformed_headers_and_payload_layout_are_rejected() {
    let config = tiny_config();
    for bytes in [b"{".as_slice(), b"[]", b"{\"x\":{},\"x\":{}}"] {
        let file = write_file(bytes, 0);
        assert!(
            validate(file.path(), &config, WeightKind::Embed)
                .unwrap_err()
                .starts_with("weights: header:")
        );
    }
    let mut oversized = NamedTempFile::new().unwrap();
    oversized.write_all(&u64::MAX.to_le_bytes()).unwrap();
    assert!(
        validate(oversized.path(), &config, WeightKind::Embed)
            .unwrap_err()
            .contains("100 MiB")
    );
    for mode in ["truncated", "overlap", "trailing"] {
        let mut header = tiny_header(WeightKind::Embed);
        if mode == "overlap" {
            header["embeddings.norm.weight"]["data_offsets"] = json!([0, 16]);
        }
        let file = fixture(&header);
        let len = file.as_file().metadata().unwrap().len();
        match mode {
            "truncated" => file.as_file().set_len(len - 1).unwrap(),
            "trailing" => file.as_file().set_len(len + 1).unwrap(),
            _ => (),
        }
        assert!(
            validate(file.path(), &config, WeightKind::Embed)
                .unwrap_err()
                .starts_with("weights: offsets:"),
            "{mode}"
        );
    }
}

// A deterministic replacement in the build step exercises the second open,
// without relying on concurrent filesystem timing. The replacement is valid
// safetensors, but no longer matches the model accepted by CPU preflight.
#[cfg(feature = "test-mlx")]
#[test]
#[serial_test::serial]
fn checked_load_rejects_parameters_replaced_after_preflight() {
    use std::fs;

    use crate::modernbert::ModernBert;
    use crate::sandbox::require_unsandboxed_mlx_runtime;

    require_unsandboxed_mlx_runtime();
    let config = tiny_config();
    for category in ["shape", "dtype", "unknown key", "missing key"] {
        let valid = tiny_header(WeightKind::Embed);
        let mut changed = valid.clone();
        let key = "final_norm.weight";
        match category {
            "shape" => changed[key]["shape"] = json!([2, 2]),
            "dtype" => changed[key]["dtype"] = json!("I32"),
            "unknown key" => {
                let end = payload_len(&changed);
                changed["unexpected.weight"] = json!({
                    "dtype": "F32", "shape": [1], "data_offsets": [end, end + 4]
                });
            }
            "missing key" => {
                // The final tensor occupies the final payload range.
                changed
                    .as_object_mut()
                    .unwrap()
                    .remove("layers.1.mlp_norm.weight");
            }
            _ => unreachable!(),
        }
        let file = tempfile::Builder::new()
            .suffix(".safetensors")
            .tempfile()
            .unwrap();
        fs::copy(fixture(&valid).path(), file.path()).unwrap();
        let error = load(file.path(), &config, WeightKind::Embed, |config| {
            fs::copy(fixture(&changed).path(), file.path()).unwrap();
            ModernBert::new(config)
        })
        .expect_err("changed checkpoint must fail after preflight");
        let expected_key = match category {
            "unknown key" => "unexpected.weight",
            "missing key" => "layers.1.mlp_norm.weight",
            _ => key,
        };
        assert!(
            error
                .what()
                .contains(&format!("weights: {category}: {expected_key}")),
            "unexpected error: {}",
            error.what()
        );
    }
}
